services:
  loki:
    image: grafana/loki:3.5.1
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/var/loki
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    volumes:
      - grafana-data:/var/lib/grafana

  grafana-alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"
    container_name: grafana-alloy
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy:ro
      - /var/log/server:/var/log/server:ro
    command:
      - --config.file=/etc/alloy/config.alloy
    depends_on:
      - loki

volumes:
  loki-data:
  grafana-data: