filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/server/*.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message

output.loki:
  hosts: ["http://loki:3100"]
  labels:
    job: "springboot"
    host: "${HOSTNAME}"
    type: "log"