auth_enabled: false
server:
  http_listen_port: 3100
  log_level: info
ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_target_size: 1048576
schema_config:
  configs:
    - from: 2025-06-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
storage_config:
  tsdb:
    path: /var/loki/index
    shard_by: tenant
    retention_period: 1440h
  filesystem:
    directory: /var/loki/chunks
    max_chunk_size: 157286400
    shared_store: filesystem
limits_config:
  enforce_metric_name: true
  reject_old_samples: true
  reject_old_samples_max_age: 168h
compactor:
  working_directory: /var/loki/compactor
  shared_store: filesystem
  retention_enabled: true